# Name of our source code branch
trigger:
  - main

# Pool of VMs for execution
pool: windows-latest


steps:
# Step 1 - python version
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.x

# Step 2 - Installing required packages
  - script: |
      pip install selenium pytest
      pip install -r YAML/requirements.txt
      pip install Functions
      pip install pytest-html
    displayName: 'Install Requirements'
    # python -m pip install pytest
    # python -m pytest



# Step 3 - test files execution + HTML report and output in JUnit and HTML formats
  - script: |
      pytest -v Tests/test_suit.py --junitxml=junit/test-results.xml --html=report.html
    displayName: 'Run tests + HTML report'


